/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMetaAPI: typeof import('~icons/meta/a-p-i')['default']
    IMetaApiDoc: typeof import('~icons/meta/api-doc')['default']
    IMetaArrowApiDoc: typeof import('~icons/meta/arrow-api-doc')['default']
    IMetaArrowCircleUp: typeof import('~icons/meta/arrow-circle-up')['default']
    IMetaBook: typeof import('~icons/meta/book')['default']
    IMetaDelete: typeof import('~icons/meta/delete')['default']
    IMetaDownArrow: typeof import('~icons/meta/down-arrow')['default']
    IMetaOpenBook: typeof import('~icons/meta/open-book')['default']
    IMetaProductDoc: typeof import('~icons/meta/product-doc')['default']
    IMetaProductManual: typeof import('~icons/meta/product-manual')['default']
    IMetaSearch: typeof import('~icons/meta/search')['default']
    IMetaSearchApi: typeof import('~icons/meta/search-api')['default']
    IMetaSearchLearning: typeof import('~icons/meta/search-learning')['default']
    IMetaSearchProduct: typeof import('~icons/meta/search-product')['default']
    IMetaTextLogo: typeof import('~icons/meta/text-logo')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
